### ISSUE TITLE
Communities

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#17]
How will communities manage their web page portals?

- Ultimately, it's editing an md file
- Make a Google Form to the content used in the md file (e.g. [CPTAC](https://raw.githubusercontent.com/wikipathways/wikipathways.github.io/main/_communities/cptac.md))?

How to manage community tags on pathway?

 - Ultimately, it's editing a list file in the WikiPathways-Database (GPML-Repo)
 - Make PR?

**Comment by khanspers** [comment]
Both of these (editing md file and list in repo) could be done by PR also. Presumably, if someone is comfortable making a PR to update the list of pathways with a community tag, they could also make a PR to update an md file. 

Alternatively, both of these could be handled by Google forms. In the case of the list of tags, the form could simply ask for a list of additional WPIDs.

**Comment by AlexanderPico** [comment]
Great point. Editing a simpe list and submitting a PR can all be done using simple GUI tools at GitHub. Should be fine for the handful of people that want to manage community lists.

**Comment by AlexanderPico** [comment]
@ariutta When I added WP554 to the COVID19.txt community file, the actions ran successfully, but...

instead of inserting "COVID19" into the frontmatter of WP554.md, the action inserted "TEST" 

I'm guessing you have some debug/testing code still in place in the action?

**Comment by ariutta** [comment]
@AlexanderPico, this appears to be working correctly now. I changed two things:
1. handle case where all communities are removed from a pathway
2. make sure to get latest data from the `wikipathways-database` repo.

For 2. above, I'm not sure why, but it appears the `copy-to-site-repo` job in the GH workflow wasn't correctly getting the latest commit from the previous `frontmatter` job. I fixed it with [this kludge](https://github.com/wikipathways/wikipathways-database/blob/c0ecd0962b0d84d267090b91f04c6e8264a73a91/.github/workflows/on_communities_change.yml#L85-L88), but I'd like to know why the kludge is even needed. It shouldn't be needed, because the `copy-to-site-repo` job explicitly lists the `frontmatter` job as a dependency: https://github.com/wikipathways/wikipathways-database/blob/c0ecd0962b0d84d267090b91f04c6e8264a73a91/.github/workflows/on_communities_change.yml#L57
